#!/bin/bash

python JetCalibration/ApplyCalibrationFactors/python/runCalibration.py --no-correction-fit --stage2 --treeName MatchAK4GenJetWithAK4JetFromPfClusters JetCalibration/Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity.root JetCalibration/Calibration_MatchAK4GenJetWithAK4JetFromPfClusters_PU200_NoZeroPtJets_FinerGranularity.root

python JetCalibration/ApplyCalibrationFactors/python/runCalibration.py --no-correction-fit --stage2 --treeName MatchAK4GenJetWithAK4JetFromPfCandidates JetCalibration/Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity.root JetCalibration/Calibration_MatchAK4GenJetWithAK4JetFromPfCandidates_PU200_NoZeroPtJets_FinerGranularity.root

python JetCalibration/ApplyCalibrationFactors/python/runCalibration.py --no-correction-fit --stage2 --treeName MatchAK4GenJetWithPhase1L1TJetFromPfClusters JetCalibration/Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity.root JetCalibration/Calibration_MatchAK4GenJetWithPhase1L1TJetFromPfClusters_PU200_NoZeroPtJets_FinerGranularity.root

python JetCalibration/ApplyCalibrationFactors/python/runCalibration.py --no-correction-fit --stage2 --treeName MatchAK4GenJetWithPhase1L1TJetFromPfCandidates JetCalibration/Trees_Calibration_PU200_Puppi_NoZeroPtJets_FinerGranularity.root JetCalibration/Calibration_MatchAK4GenJetWithPhase1L1TJetFromPfCandidates_PU200_NoZeroPtJets_FinerGranularity.root